project:
  type: website
  preview:
    port: 4200
  render:
    - index.qmd
    - "pages/*.qmd"
  output-dir: site
  execute-dir: project
  post-render:
    - scripts/move_jupyter_notebooks.py
    - scripts/standardize_jupyter_notebook_cell_ids.py
    - jupyter nbconvert --clear-output --inplace notebooks/*.ipynb

filters:
  - black-formatter
  - add-code-files

date: 2023-08-26
date-modified: last-modified
date-format: long
license: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
abstract-title: Summary

website:
  title: "CCN 2023 | Tutorial"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: pages/introducing_pca.qmd
        text: Introducing PCA
      - href: pages/exploring_neural_data.qmd
        text: Exploring neural data
      - href: pages/dealing_with_noise.qmd
        text: Dealing with noise
      - href: pages/comparing_representations.qmd
        text: Comparing representations
      - href: pages/reference.qmd
        text: Reference
    tools:
      - icon: github
        href: https://github.com/BonnerLab/ccn-tutorial
  repo-url: https://github.com/BonnerLab/ccn-tutorial
  repo-actions: [edit, issue]
  search:
    type: textbox

format:
  html:
    theme:
      light: flatly
      dark: darkly
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 300px
      gutter-width: 3em
    code-block-bg: true
    highlight-style: atom-one
    html-math-method: katex
    smooth-scroll: false
    toc: true
    toc-depth: 4
    toc-title: Contents
    toc-expand: 1
    code-fold: true
    code-copy: true
    code-tools:
      source: repo
      toggle: true
      caption: Code blocks
    fig-align: center
    fig-format: svg
    fig-responsive: true
    fig-width: 7
    fig-height: 5
    notebook-links: true
    citations-hover: true
    footnotes-hover: true
    keep-ipynb: false
    title-block-banner: true
  ipynb:
    code-annotations: none

execute:
  enabled: true
  cache: true
  warning: false
  error: false
jupyter: python3
