name: publish
run-name: ${{ github.actor }}
on: workflow_dispatch

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install -y ffmpeg

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"
      - run: |
          pip install .

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.330
          tinytex: true
      - run: |
          quarto --version

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}